// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    appId: '1:192633317936:web:7cdb2b780d6055a89a1bf5',
    messagingSenderId: '192633317936',
    projectId: 'bddogclub',
    authDomain: 'bddogclub.firebaseapp.com',
    storageBucket: 'bddogclub.firebasestorage.app',
    measurementId: 'G-0JC010ZVGY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    appId: '1:192633317936:android:f9fdd77950987d319a1bf5',
    messagingSenderId: '192633317936',
    projectId: 'bddogclub',
    storageBucket: 'bddogclub.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    appId: '1:192633317936:ios:18a12415dd2b9fe79a1bf5',
    messagingSenderId: '192633317936',
    projectId: 'bddogclub',
    storageBucket: 'bddogclub.firebasestorage.app',
    iosBundleId: 'com.example.cruddogclub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    appId: '1:192633317936:ios:18a12415dd2b9fe79a1bf5',
    messagingSenderId: '192633317936',
    projectId: 'bddogclub',
    storageBucket: 'bddogclub.firebasestorage.app',
    iosBundleId: 'com.example.cruddogclub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    appId: '1:192633317936:web:d2973af2296aeb8b9a1bf5',
    messagingSenderId: '192633317936',
    projectId: 'bddogclub',
    authDomain: 'bddogclub.firebaseapp.com',
    storageBucket: 'bddogclub.firebasestorage.app',
    measurementId: 'G-DL7VM3X1Y7',
  );
}
